include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/packaging-docker/docker-build.yml'

stages:
  - pre-package
  - package
  - post-package

.docker-build:
  variables:
    IMAGE_NAME_VARIABLE_NAME: BACKUP_POSTGRESQL_IMAGE_NAME
    IMAGE_TAG_VARIABLE_NAME: BACKUP_POSTGRESQL_IMAGE_TAG
