services:
  backup-postgresql:
    image: ${BACKUP_POSTGRESQL_IMAGE_NAME:-registry.gitlab.com/redmic-project/postgres/backup-postgresql}:${BACKUP_POSTGRESQL_IMAGE_TAG:-latest}
    environment:
      POSTGRES_HOSTNAME:
      POSTGRES_PORT:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      EXTRA_DUMP_PARAMS:
      POSTGRES_DUMP_PATH:
      POSTGRES_PASS_FILE:
      DUMP_FILENAME:
      BUCKET_BACKUP_DB:
      UPLOAD_ENDPOINT_URL:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION:
      AWS_OUTPUT:
      PUSHGATEWAY_HOST:
      PUSHGATEWAY_JOB:
    networks:
      postgres-net:
      metric-net:
      minio-net:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: ${BACKUP_POSTGRESQL_RESTART_DELAY:-30s}
      resources:
        limits:
          cpus: '${BACKUP_POSTGRESQL_RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${BACKUP_POSTGRESQL_RESOURCES_LIMITS_MEMORY:-256M}
        reservations:
          cpus: '${BACKUP_POSTGRESQL_RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${BACKUP_POSTGRESQL_RESOURCES_RESERVATIONS_MEMORY:-64M}

networks:
  postgres-net:
    name: ${POSTGRES_NET_NAME}
    driver: ${POSTGRES_NET_DRIVER:-overlay}
    external: true

  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    driver: ${METRIC_NET_DRIVER:-overlay}
    external: true

  minio-net:
    name: ${MINIO_NET_NAME:-minio-net}
    driver: ${MINIO_NET_DRIVER:-overlay}
    external: true
